import Header from '@/components/Header'
import '@/style/globals.scss'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from "next/font/google";

export const notoSansKr = Noto_Sans_KR({
  weight: ['500'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={notoSansKr.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
